[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "curl -fsSL https://get.pnpm.io/install.sh | SHELL=\"$(which bash)\" sh -s -- --version 9.12.1 --bin-dir /usr/local/bin",
  "pnpm config set verify-store-integrity false",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter @ai-agent-village-monitor/server build"
]

[start]
cmd = "pnpm --filter @ai-agent-village-monitor/server start"

[variables]
NODE_ENV = "production"
PNPM_VERSION = "9"
