// AUTO-GENERATED by scripts/generate-pixellab-manifest.mjs
// Do not edit manually.

export const pixellabAnimationMetadata = {
  agents: {
    artisan: {
      walking: {
        south: 6,
        east: 6,
        'south-east': 6,
        'north-west': 6,
        west: 6,
        north: 6,
        'south-west': 6,
        'north-east': 6,
      },
    },
    explorer: {
      walking: {
        south: 6,
        west: 6,
        'south-west': 6,
        'south-east': 6,
        'north-west': 6,
        north: 6,
      },
    },
    guardian: {},
    mystic: {
      walking: {
        north: 6,
        south: 6,
        'north-east': 6,
        'south-west': 6,
        'north-west': 6,
        west: 6,
      },
    },
    scholar: {
      walking: {
        'south-east': 6,
        'south-west': 6,
        'north-west': 6,
        south: 6,
        north: 6,
        west: 6,
        east: 6,
        'north-east': 6,
      },
    },
    'signal-weaver': {},
  },
  emotes: {
    awakening: {
      'breathing-idle': {
        south: 4,
        east: 4,
        north: 4,
        west: 4,
      },
    },
    communication: {
      'breathing-idle': {
        north: 4,
        west: 4,
        south: 4,
      },
    },
    'deep-thinking': {},
    dreaming: {
      'breathing-idle': {
        east: 4,
        north: 4,
        south: 4,
        west: 4,
      },
    },
    eureka: {
      fireball: {
        south: 6,
        west: 6,
        east: 6,
        north: 6,
      },
    },
    'flow-state': {},
    frustration: {
      'cross-punch': {
        south: 6,
        east: 6,
        west: 6,
        north: 6,
      },
    },
    'learning-growth': {
      'breathing-idle': {
        east: 4,
        west: 4,
        south: 4,
        north: 4,
      },
    },
  },
  'bug-bots': {
    assigned: {
      'breathing-idle': {
        east: 4,
        north: 4,
        west: 4,
        south: 4,
      },
    },
    progress: {
      'fight-stance-idle-8-frames': {
        north: 8,
        east: 8,
        south: 8,
        west: 8,
      },
    },
    resolved: {
      fireball: {
        east: 6,
        west: 6,
        south: 6,
        north: 6,
      },
    },
    spawn: {
      'breathing-idle': {
        east: 4,
        north: 4,
        south: 4,
        west: 4,
      },
    },
  },
  houses: {
    cs: {},
    generic: {},
    go: {},
    java: {},
    js: {},
    py: {},
    rb: {},
    ts: {},
  },
} as const;

export type PixellabAnimationMetadata = typeof pixellabAnimationMetadata;
