blank_issues_enabled: false
contact_links:
  # NOTE: Update this link after repo transfer to h3ro-dev
  - name: Questions & Discussions
    url: https://github.com/CryptoJym/ai-agent-village-monitor/discussions
    about: Ask questions and start discussions here.
