/**
 * Tilemap Generation Types
 * Defines the data structures for procedurally generated tilemaps in the AI Agent Village Monitor RPG
 */

// ===== Core Tilemap Types =====

/**
 * Represents a single layer in the tilemap
 * Layers are rendered in order: ground -> walls -> decorations -> above-player
 */
export interface TilemapLayer {
  /** Layer name (e.g., "ground", "walls", "decorations") */
  name: string;
  /** Tile IDs in row-major order (y * width + x) */
  data: number[];
  /** Layer width in tiles */
  width: number;
  /** Layer height in tiles */
  height: number;
  /** Whether this layer is visible */
  visible: boolean;
  /** Layer opacity (0-1) */
  opacity: number;
  /** Z-index for rendering order */
  zIndex?: number;
  /** Custom properties for this layer */
  properties?: Record<string, any>;
}

/**
 * Complete tilemap data structure compatible with Phaser
 */
export interface TilemapData {
  /** Map width in tiles */
  width: number;
  /** Map height in tiles */
  height: number;
  /** Width of each tile in pixels */
  tileWidth: number;
  /** Height of each tile in pixels */
  tileHeight: number;
  /** All layers in the tilemap */
  layers: TilemapLayer[];
  /** Collision/passability map (true = blocked, false = passable) */
  collision: boolean[];
  /** Map-level custom properties */
  properties: Record<string, any>;
  /** Optional tileset reference */
  tilesets?: TilesetReference[];
}

/**
 * Reference to a tileset used in the map
 */
export interface TilesetReference {
  /** First global tile ID in this tileset */
  firstgid: number;
  /** Tileset name */
  name: string;
  /** Path to tileset image */
  image?: string;
  /** Tile width in pixels */
  tileWidth: number;
  /** Tile height in pixels */
  tileHeight: number;
  /** Number of tiles in the tileset */
  tileCount: number;
  /** Number of columns in the tileset */
  columns: number;
}

/**
 * Mapping of tile types to tile IDs
 * Used to convert semantic tile types to actual tile IDs
 */
export interface TileMapping {
  /** 4-bit mask to tile ID mapping for walls (see autoTile.ts) */
  wallTiles: Record<number, number>;
  /** Floor tile IDs by room type */
  floorTiles: number[];
  /** Door tiles by direction */
  doorTiles: {
    north: number;
    south: number;
    east: number;
    west: number;
  };
  /** Decoration tile IDs by type */
  decorationTiles: Record<string, number>;
  /** Shadow/depth effect tiles */
  shadowTiles?: {
    wallShadow: number;
    cornerShadow: number;
  };
}

// ===== Room & Corridor Types (for BSP integration) =====

/**
 * Room types that determine decoration and floor tile selection
 */
export type RoomType =
  | 'workspace'    // Desks, monitors, keyboards
  | 'library'      // Bookshelves, reading tables
  | 'vault'        // Safes, filing cabinets
  | 'laboratory'   // Equipment, test tubes
  | 'hallway'      // Simple corridor
  | 'entrance';    // Entry area

/**
 * Rectangle representing a room or area
 */
export interface Rectangle {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * A room generated by BSP algorithm
 */
export interface Room {
  /** Unique room identifier */
  id: string;
  /** Room bounds */
  bounds: Rectangle;
  /** Room type (determines decorations) */
  type: RoomType;
  /** Center point of the room */
  center: { x: number; y: number };
  /** Connected room IDs */
  connections?: string[];
  /** Custom properties for this room */
  properties?: Record<string, any>;
}

/**
 * Direction enum for corridors and doors
 */
export enum Direction {
  North = 'north',
  South = 'south',
  East = 'east',
  West = 'west',
}

/**
 * A corridor connecting two rooms
 */
export interface Corridor {
  /** Start position */
  start: { x: number; y: number };
  /** End position */
  end: { x: number; y: number };
  /** Width of the corridor in tiles */
  width: number;
  /** Rooms this corridor connects */
  connects?: [string, string];
  /** Corridor segments (for L-shaped corridors) */
  segments?: CorridorSegment[];
}

/**
 * A segment of a corridor (for L-shaped paths)
 */
export interface CorridorSegment {
  start: { x: number; y: number };
  end: { x: number; y: number };
  direction: Direction;
}

// ===== Decoration Types =====

/**
 * Placement strategy for decorations
 */
export type PlacementRule =
  | 'against-wall'   // Place against nearest wall
  | 'centered'       // Place in center of room
  | 'corner'         // Place in room corners
  | 'scattered';     // Random placement

/**
 * A decoration/furniture item
 */
export interface Decoration {
  /** Tile ID for this decoration */
  tileId: number;
  /** Position in the map */
  position: { x: number; y: number };
  /** Whether this decoration blocks movement */
  blocksMovement: boolean;
  /** Multi-tile decoration dimensions (if > 1x1) */
  dimensions?: { width: number; height: number };
  /** Z-index offset for layering */
  zOffset?: number;
}

/**
 * Catalog of decorations for a room type
 */
export interface DecorationCatalog {
  /** Room type this catalog applies to */
  roomType: RoomType;
  /** Available decoration items */
  items: DecorationItem[];
}

/**
 * Definition of a decoration item
 */
export interface DecorationItem {
  /** Unique identifier */
  id: string;
  /** Display name */
  name: string;
  /** Tile ID or range of tile IDs */
  tileId: number | number[];
  /** Placement strategy */
  placement: PlacementRule;
  /** Whether it blocks movement */
  blocksMovement: boolean;
  /** Size in tiles */
  size: { width: number; height: number };
  /** Spawn probability (0-1) */
  probability: number;
  /** Minimum room size required */
  minRoomSize?: number;
}

// ===== RNG Types =====

/**
 * Seeded random number generator interface
 * Allows for reproducible map generation
 */
export interface SeededRNG {
  /** Generate random float between 0 and 1 */
  random(): number;
  /** Generate random integer between min (inclusive) and max (exclusive) */
  randomInt(min: number, max: number): number;
  /** Pick random item from array */
  pick<T>(array: T[]): T;
  /** Shuffle array in place */
  shuffle<T>(array: T[]): T[];
  /** Get current seed */
  getSeed(): string;
}

// ===== Generation Options =====

/**
 * Options for tilemap generation
 */
export interface TilemapOptions {
  /** Tile dimensions */
  tileWidth: number;
  tileHeight: number;
  /** Tile mapping configuration */
  tileMapping: TileMapping;
  /** Whether to generate decorations */
  includeDecorations?: boolean;
  /** Decoration density (0-1) */
  decorationDensity?: number;
  /** Whether to include shadows */
  includeShadows?: boolean;
  /** Layer configuration */
  layers?: {
    ground: boolean;
    walls: boolean;
    decorations: boolean;
    abovePlayer: boolean;
  };
  /** Custom properties to include */
  properties?: Record<string, any>;
}

// ===== Tile Constants =====

/**
 * Standard tile IDs (can be overridden by TileMapping)
 */
export const DEFAULT_TILE_IDS = {
  EMPTY: 0,
  FLOOR_DEFAULT: 1,
  FLOOR_CORRIDOR: 2,
  WALL_FULL: 16,
  DOOR_NORTH: 32,
  DOOR_SOUTH: 33,
  DOOR_EAST: 34,
  DOOR_WEST: 35,
  SHADOW: 48,
} as const;

/**
 * 4-bit auto-tiling masks
 * Bits: N=1, E=2, S=4, W=8
 */
export const AUTOTILE_MASKS = {
  NONE: 0,        // 0000 - No adjacent walls
  N: 1,           // 0001 - North
  E: 2,           // 0010 - East
  NE: 3,          // 0011 - North + East
  S: 4,           // 0100 - South
  NS: 5,          // 0101 - North + South
  SE: 6,          // 0110 - South + East
  NSE: 7,         // 0111 - North + South + East
  W: 8,           // 1000 - West
  NW: 9,          // 1001 - North + West
  EW: 10,         // 1010 - East + West
  NEW: 11,        // 1011 - North + East + West
  SW: 12,         // 1100 - South + West
  NSW: 13,        // 1101 - North + South + West
  SEW: 14,        // 1110 - South + East + West
  ALL: 15,        // 1111 - All directions
} as const;

/**
 * Layer names used throughout the system
 */
export const LAYER_NAMES = {
  GROUND: 'ground',
  WALLS: 'walls',
  DECORATIONS: 'decorations',
  ABOVE_PLAYER: 'above-player',
  COLLISION: 'collision',
} as const;
